Repository wanted-pre-onboarding-backend-team-7/AROUND-MEAL, pull requests merged in 2024-09, with the labels that each got.

#75 [REFACTOR] 스프링 시큐리티 예외처리 방식 변경 및 일부 테스트 완료
  src/main/java/com/lucky/around/meal/common/config/SpringSecurityConfig.java
  src/main/java/com/lucky/around/meal/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomLogoutHandler.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/lucky/around/meal/common/security/util/CookieProvider.java
  src/main/java/com/lucky/around/meal/common/security/util/JwtProvider.java
  src/main/java/com/lucky/around/meal/exception/CustomExceptionHandler.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/SecurityExceptionType.java
  src/main/java/com/lucky/around/meal/service/JwtService.java
  src/test/java/com/lucky/around/meal/common/security/util/CookieProviderTest.java
  src/test/java/com/lucky/around/meal/common/security/util/JwtProviderTest.java
  src/test/java/com/lucky/around/meal/service/MemberServiceTest.java
Labels: 🔨 Refactor

#73 [REFACTOR] 시군구 csv 파일 업로드 방식 변경
  build.gradle
  src/main/java/com/lucky/around/meal/controller/RegionController.java
  src/main/java/com/lucky/around/meal/controller/record/RegionRecord.java
  src/main/java/com/lucky/around/meal/repository/RegionRepository.java
  src/main/java/com/lucky/around/meal/service/CsvRegionService.java
  src/main/java/com/lucky/around/meal/service/JwtService.java
  src/main/java/com/lucky/around/meal/service/RegionService.java
Labels: 🔨 Refactor

#78 [FIX] 파일 충돌 해결
  src/main/java/com/lucky/around/meal/service/JwtService.java
Labels: 🪄 Fix

#84 [REFACTOR] 데이터 파이프라인 리팩토링
  src/main/java/com/lucky/around/meal/datapipeline/DataPipeLineService.java
  src/main/java/com/lucky/around/meal/datapipeline/DataProcessService.java
  src/main/java/com/lucky/around/meal/datapipeline/RawDataLoadService.java
  src/main/java/com/lucky/around/meal/entity/Restaurant.java
Labels: 🔨 Refactor, 📊 Data

#83 [FEAT] 시군구 목록 조회 API 고도화
  src/main/java/com/lucky/around/meal/Application.java
  src/main/java/com/lucky/around/meal/common/config/CacheConfig.java
  src/main/java/com/lucky/around/meal/service/RegionService.java
Labels: ✨ Feature, 🔨 Refactor

#88 [FEAT] 맛집 상세정보 고도화(조회수 기준)
  build.gradle
  src/main/java/com/lucky/around/meal/cache/service/ViewCountService.java
  src/main/java/com/lucky/around/meal/common/config/CacheConfig.java
  src/main/java/com/lucky/around/meal/controller/RestaurantController.java
  src/main/java/com/lucky/around/meal/controller/request/RestaurantDetailsRequestDto.java
  src/main/java/com/lucky/around/meal/controller/response/RatingResponseDto.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: ✨ Feature

#92 [FIX] 데이터 파이프라인 개선
  src/main/java/com/lucky/around/meal/datapipeline/DataPipeLineService.java
  src/main/java/com/lucky/around/meal/datapipeline/DataProcessService.java
  src/main/java/com/lucky/around/meal/datapipeline/RawDataLoadService.java
Labels: 🪄 Fix, 🔨 Refactor, 📊 Data

#93 [REFACTOR] 평가 수 기준 캐싱 방식 변경
  src/main/java/com/lucky/around/meal/cache/entity/RestaurantForRedis.java
  src/main/java/com/lucky/around/meal/cache/repository/RestaurantForRedisRepository.java
  src/main/java/com/lucky/around/meal/cache/service/RatingCountService.java
  src/main/java/com/lucky/around/meal/common/config/RedisConfig.java
  src/main/java/com/lucky/around/meal/controller/RestaurantController.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/CommonExceptionType.java
  src/main/java/com/lucky/around/meal/service/RatingService.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: 🔨 Refactor

#97 [FEAT] 평가 생성 API 중복 예외 처리
  src/main/java/com/lucky/around/meal/controller/RatingController.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/RatingException.java
  src/main/java/com/lucky/around/meal/repository/RatingRepository.java
  src/main/java/com/lucky/around/meal/service/RatingService.java
Labels: ✨ Feature, 🔨 Refactor

#102 [REFACTOR] 리스트 수집 방식을 변경
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: 🔨 Refactor

#104 [FEAT] 사용자 설정 업데이트(맛집 추천 여부)
  src/main/java/com/lucky/around/meal/controller/MemberController.java
  src/main/java/com/lucky/around/meal/entity/Member.java
  src/main/java/com/lucky/around/meal/service/MemberService.java
Labels: ✨ Feature

#106 [REFACTOR] 조회수 관리 개선
  src/main/java/com/lucky/around/meal/cache/service/ViewCountService.java
  src/main/java/com/lucky/around/meal/controller/RestaurantController.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: ✨ Feature, 🔨 Refactor

#107 [TEST] 평가 생성 API 테스트 코드 추가
  src/main/java/com/lucky/around/meal/common/config/CacheConfig.java
  src/test/java/com/lucky/around/meal/service/RatingServiceTest.java
Labels: ✅ Test, 📊 Data

#108 [TEST] 맛집 상세 조회 및 조회수 캐싱 기능 테스트
  src/test/java/com/lucky/around/meal/cache/service/ViewCountServiceTest.java
  src/test/java/com/lucky/around/meal/service/RestaurantServiceTest.java
Labels: ✅ Test

#110 [REFACTOR] 파이프라인 비동기화
  src/main/java/com/lucky/around/meal/Application.java
  src/main/java/com/lucky/around/meal/datapipeline/AsyncConfig.java
  src/main/java/com/lucky/around/meal/datapipeline/DataPipeLineService.java
  src/main/java/com/lucky/around/meal/datapipeline/DataProcessService.java
  src/main/java/com/lucky/around/meal/datapipeline/RawDataLoadService.java
Labels: 🔨 Refactor, 📊 Data

#112 [FIX] cron 수식 필드 6개가 되도록 수정
  src/main/java/com/lucky/around/meal/common/config/SpringSecurityConfig.java
  src/main/java/com/lucky/around/meal/service/RecommendRestaurantService.java
Labels: 🪄 Fix

#114 [DOCS] 리드미 수정
  README.md
Labels: 📃 Docs

#116 [FEAT] 맛집 추천 로직 비동기 처리 및 추천 로직 개선
  src/main/java/com/lucky/around/meal/repository/RestaurantRepository.java
  src/main/java/com/lucky/around/meal/service/RecommendRestaurantService.java
Labels: ✨ Feature

#119 [REFACTOR] 맛집 리스트 조회 API 리팩터링
  src/main/java/com/lucky/around/meal/common/util/GeometryUtil.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/RestaurantExceptionType.java
  src/main/java/com/lucky/around/meal/repository/RestaurantRepository.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: 🔨 Refactor
