Repository wanted-pre-onboarding-backend-team-7/AROUND-MEAL, pull requests merged in 2024-08, with the labels that each got.

#11 [CHORE] build.gradle 의존성 추가
  build.gradle
Labels: 🧹 Chore

#16 [FEAT] Region, Restaurant 엔티티 설계
  src/main/java/com/lucky/around/meal/entity/Region.java
  src/main/java/com/lucky/around/meal/entity/Restaurant.java
  src/main/java/com/lucky/around/meal/entity/dummy.txt
  src/main/java/com/lucky/around/meal/entity/enums/Category.java
  src/main/resources/application.yml
Labels: ✨ Feature

#22 [FEAT] 평가 엔티티 설계
  src/main/java/com/lucky/around/meal/entity/Rating.java
Labels: ✨ Feature

#24 [FEAT] 맛집 데이터 수집, 맛집 데이터 전처리
  build.gradle
  src/main/java/com/lucky/around/meal/common/WebClientConfig.java
  src/main/java/com/lucky/around/meal/common/dummy.txt
  src/main/java/com/lucky/around/meal/controller/data/DataController.java
  src/main/java/com/lucky/around/meal/controller/dummy.txt
  src/main/java/com/lucky/around/meal/entity/Member.java
  src/main/java/com/lucky/around/meal/entity/Rating.java
  src/main/java/com/lucky/around/meal/entity/enums/MemberRole.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/DataExceptionType.java
  src/main/java/com/lucky/around/meal/service/data/DataService.java
  src/main/java/com/lucky/around/meal/service/dummy.txt
  src/main/resources/application.yml
Labels: ✨ Feature, 📊 Data

#25 [FEAT] 맛집 데이터 저장
  src/main/java/com/lucky/around/meal/controller/data/DataController.java
  src/main/java/com/lucky/around/meal/entity/Region.java
  src/main/java/com/lucky/around/meal/entity/enums/Category.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/RegionExceptionType.java
  src/main/java/com/lucky/around/meal/repository/RegionRepository.java
  src/main/java/com/lucky/around/meal/repository/RestaurantRepository.java
  src/main/java/com/lucky/around/meal/repository/dummy.txt
  src/main/java/com/lucky/around/meal/service/data/DataService.java
Labels: ✨ Feature, 📊 Data

#26 [FEAT] 시군구 목록 전체 조회 API 기능 구현
  build.gradle
  src/main/java/com/lucky/around/meal/controller/RegionController.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/CsvRegionExceptionType.java
  src/main/java/com/lucky/around/meal/service/CsvRegionService.java
  src/main/java/com/lucky/around/meal/service/RegionService.java
  src/main/resources/region/sgg_lat_lon.csv
Labels: ✨ Feature, 📃 Docs

#28 [FEAT] 맛집 데이터 파이프라인 스케줄러 설정
  src/main/java/com/lucky/around/meal/Application.java
  src/main/java/com/lucky/around/meal/controller/data/DataController.java
  src/main/java/com/lucky/around/meal/controller/dummy.txt
  src/main/java/com/lucky/around/meal/exception/exceptionType/DataExceptionType.java
  src/main/java/com/lucky/around/meal/service/data/DataService.java
Labels: ✨ Feature

#31 [FEAT] 맛집 목록 API 구현
  build.gradle
  src/main/java/com/lucky/around/meal/controller/RestaurantController.java
  src/main/java/com/lucky/around/meal/controller/dto/GetRestaurantsDto.java
  src/main/java/com/lucky/around/meal/controller/dummy.txt
  src/main/java/com/lucky/around/meal/entity/Restaurant.java
  src/main/java/com/lucky/around/meal/repository/RestaurantRepository.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#33 [FEAT] Region, Restaurant 연관관계 삭제
  src/main/java/com/lucky/around/meal/entity/Restaurant.java
  src/main/java/com/lucky/around/meal/service/data/DataService.java
Labels: ✨ Feature

#36 [FEAT] 맛집 상세목록 조회 구현
  src/main/java/com/lucky/around/meal/controller/RestaurantController.java
  src/main/java/com/lucky/around/meal/controller/response/RatingResponseDto.java
  src/main/java/com/lucky/around/meal/controller/response/RestaurantDetailResponseDto.java
  src/main/java/com/lucky/around/meal/entity/Rating.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/RestaurantExceptionType.java
  src/main/java/com/lucky/around/meal/repository/RatingRepository.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: ✨ Feature

#38 [FIX] 문법 오류 수정 및 Entity 수정에 따른 DTO 수정
  src/main/java/com/lucky/around/meal/controller/RestaurantController.java
  src/main/java/com/lucky/around/meal/controller/response/RestaurantDetailResponseDto.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: 🪄 Fix

#40 [TEST] 맛집 상세 정보 조회 테스트
  src/main/java/com/lucky/around/meal/entity/Rating.java
  src/test/java/com/lucky/around/meal/service/RestaurantServiceTest.java
Labels: ✅ Test

#41 [FEAT] Point를 사용하여 거리를 계산하도록 엔티티 및 관련 코드 변경
  src/main/java/com/lucky/around/meal/common/config/GeometryConfig.java
  src/main/java/com/lucky/around/meal/common/util/GeometryUtil.java
  src/main/java/com/lucky/around/meal/entity/Restaurant.java
  src/main/java/com/lucky/around/meal/repository/RegionRepository.java
  src/main/java/com/lucky/around/meal/repository/RestaurantRepository.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
  src/main/java/com/lucky/around/meal/service/data/DataService.java
  src/test/java/com/lucky/around/meal/service/RestaurantServiceTest.java
Labels: ✨ Feature

#43 [FEAT] 사용자 로그인 API 구현
  build.gradle
  src/main/java/com/lucky/around/meal/common/config/RedisConfig.java
  src/main/java/com/lucky/around/meal/common/config/SpringSecurityConfig.java
  src/main/java/com/lucky/around/meal/common/security/details/PrincipalDetails.java
  src/main/java/com/lucky/around/meal/common/security/details/PrincipalDetailsService.java
  src/main/java/com/lucky/around/meal/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/lucky/around/meal/common/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomLogoutHandler.java
  src/main/java/com/lucky/around/meal/common/security/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/lucky/around/meal/common/security/record/JwtRecord.java
  src/main/java/com/lucky/around/meal/common/security/redis/RefreshToken.java
  src/main/java/com/lucky/around/meal/common/security/redis/RefreshTokenRepository.java
  src/main/java/com/lucky/around/meal/common/security/util/CookieProvider.java
  src/main/java/com/lucky/around/meal/common/security/util/JwtProvider.java
  src/main/java/com/lucky/around/meal/controller/record/LoginRecord.java
  src/main/java/com/lucky/around/meal/entity/Member.java
  src/main/java/com/lucky/around/meal/exception/CustomExceptionHandler.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/SecurityExceptionType.java
  src/main/java/com/lucky/around/meal/repository/MemberRepository.java
  src/main/resources/application.yml
Labels: ✨ Feature

#45 [FIX] SpringSecurityConfig 권한 수정
  src/main/java/com/lucky/around/meal/common/config/SpringSecurityConfig.java
Labels: 🪄 Fix

#47 [REFACTOR] Member 엔티티 수정
  src/main/java/com/lucky/around/meal/common/security/details/PrincipalDetails.java
  src/main/java/com/lucky/around/meal/common/security/details/PrincipalDetailsService.java
  src/main/java/com/lucky/around/meal/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/lucky/around/meal/controller/record/LoginRecord.java
  src/main/java/com/lucky/around/meal/entity/Member.java
  src/main/java/com/lucky/around/meal/repository/MemberRepository.java
Labels: 🔨 Refactor

#51 [FIX] MemberReposity 수정
  src/main/java/com/lucky/around/meal/repository/MemberRepository.java
Labels: 🐞 BugFix

#52 [FEAT] 사용자 회원가입 API 구현
  src/main/java/com/lucky/around/meal/controller/MemberController.java
  src/main/java/com/lucky/around/meal/controller/record/RegisterRecord.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/RegisterExceptionType.java
  src/main/java/com/lucky/around/meal/repository/MemberRepository.java
  src/main/java/com/lucky/around/meal/service/MemberService.java
Labels: ✨ Feature

#53 [FEAT] 평가 생성 API 기능 구현
  src/main/java/com/lucky/around/meal/controller/RatingController.java
  src/main/java/com/lucky/around/meal/controller/request/RatingRequestDto.java
  src/main/java/com/lucky/around/meal/controller/response/RatingResponseDto.java
  src/main/java/com/lucky/around/meal/repository/MemberRepository.java
  src/main/java/com/lucky/around/meal/repository/RatingRepository.java
  src/main/java/com/lucky/around/meal/service/RatingService.java
Labels: 🪄 Fix, ✨ Feature

#56 [REFACTOR] 원본 테이블, 운영 테이블 분리
  src/main/java/com/lucky/around/meal/datapipeline/DataProcessingService.java
  src/main/java/com/lucky/around/meal/datapipeline/HashUtil.java
  src/main/java/com/lucky/around/meal/datapipeline/RawDataSaveService.java
  src/main/java/com/lucky/around/meal/datapipeline/RawRestaurant.java
  src/main/java/com/lucky/around/meal/datapipeline/RawRestaurantRepository.java
  src/main/java/com/lucky/around/meal/service/data/DataService.java
Labels: 🔨 Refactor, 📊 Data

#55 [REFACTOR] 평가 생성 API 수정 및 평점 평균 계산 추가
  src/main/java/com/lucky/around/meal/controller/response/RestaurantDetailResponseDto.java
  src/main/java/com/lucky/around/meal/entity/Restaurant.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/MemberExceptionType.java
  src/main/java/com/lucky/around/meal/service/RatingService.java
  src/main/java/com/lucky/around/meal/service/RestaurantService.java
Labels: 🔨 Refactor

#57 [FEAT] 사용자 정보 API 구현 및 jwt 만료기한 설정 수정
  src/main/java/com/lucky/around/meal/common/config/SpringSecurityConfig.java
  src/main/java/com/lucky/around/meal/common/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/lucky/around/meal/common/security/util/JwtProvider.java
  src/main/java/com/lucky/around/meal/controller/MemberController.java
  src/main/java/com/lucky/around/meal/controller/dto/MemberDto.java
  src/main/java/com/lucky/around/meal/entity/Member.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/SecurityExceptionType.java
  src/main/java/com/lucky/around/meal/service/MemberService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#65 [REFACTOR] 평가 생성 시 로그인 정보 요청 추가
  src/main/java/com/lucky/around/meal/controller/RatingController.java
  src/main/java/com/lucky/around/meal/controller/request/RatingRequestDto.java
  src/main/java/com/lucky/around/meal/service/RatingService.java
Labels: ✨ Feature, 🔨 Refactor

#66 [FEAT] 리프레시 토큰 발급 기능 구현
  src/main/java/com/lucky/around/meal/common/security/details/PrincipalDetails.java
  src/main/java/com/lucky/around/meal/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/lucky/around/meal/common/security/util/CookieProvider.java
  src/main/java/com/lucky/around/meal/common/security/util/JwtProvider.java
  src/main/java/com/lucky/around/meal/controller/MemberController.java
  src/main/java/com/lucky/around/meal/service/JwtService.java
  src/main/java/com/lucky/around/meal/service/MemberService.java
Labels: ✨ Feature

#69 [TEST] 사용자 회원가입 API , 사용자 상세 정보 API 테스트 코드 작성
  src/main/java/com/lucky/around/meal/controller/MemberController.java
  src/main/java/com/lucky/around/meal/service/JwtService.java
  src/main/java/com/lucky/around/meal/service/MemberService.java
  src/test/java/com/lucky/around/meal/service/MemberServiceTest.java
Labels: ✅ Test

#70 [FEAT] 사용자 설정 업데이트
  src/main/java/com/lucky/around/meal/common/redis/RedisRepository.java
  src/main/java/com/lucky/around/meal/controller/LocationController.java
  src/main/java/com/lucky/around/meal/controller/request/MemberLocationRequestDto.java
  src/main/java/com/lucky/around/meal/controller/request/StaticLocationRequestDto.java
  src/main/java/com/lucky/around/meal/controller/response/LocationResponseDto.java
  src/main/java/com/lucky/around/meal/controller/response/StaticLocationResponseDto.java
  src/main/java/com/lucky/around/meal/entity/Member.java
  src/main/java/com/lucky/around/meal/exception/exceptionType/MemberExceptionType.java
  src/main/java/com/lucky/around/meal/service/JwtService.java
  src/main/java/com/lucky/around/meal/service/LocationService.java
  src/main/java/com/lucky/around/meal/service/MemberService.java
  src/main/java/com/lucky/around/meal/service/RatingService.java
Labels: ✨ Feature
